# Generated by Django 3.0.4 on 2020-05-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_computer_electronic_headphones_television'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronic',
            name='average_rating',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electronic',
            name='review_count',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
