# Generated by Django 3.0.4 on 2020-05-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200505_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronic',
            name='image_path',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
