# Generated by Django 3.0.4 on 2020-05-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_electronic_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='image',
        ),
        migrations.AddField(
            model_name='laptop',
            name='image_url',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
