# Generated by Django 3.0.4 on 2020-05-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20200509_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
        migrations.AddField(
            model_name='laptop',
            name='screen_size',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='electronic',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
