# Generated by Django 3.0.4 on 2020-05-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_book_top_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronic',
            name='top_seller',
            field=models.BooleanField(default=False),
        ),
    ]
