# Generated by Django 3.0.4 on 2020-05-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20200528_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_rating',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='review_count',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
