# Generated by Django 3.0.4 on 2020-05-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20200529_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronic',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
