# Generated by Django 3.0.4 on 2020-05-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20200529_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_path',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_path',
            field=models.CharField(default='', max_length=64),
        ),
    ]
