# Generated by Django 3.0.4 on 2020-05-29 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20200529_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='image_url',
            new_name='generic_image_path',
        ),
    ]
