# Generated by Django 3.0.4 on 2020-05-29 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20200529_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='image_path',
            new_name='generic_image_path',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image_path',
            new_name='generic_image_path',
        ),
    ]
