# Generated by Django 3.0.4 on 2020-05-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20200529_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='product_image_path',
            field=models.CharField(default='', max_length=64),
        ),
    ]
