# Generated by Django 3.0.4 on 2020-05-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_laptop_product_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='product_image_path',
            field=models.CharField(default='', max_length=64),
        ),
    ]
