# Generated by Django 3.0.4 on 2020-06-15 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_auto_20200615_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcounter',
            old_name='duplicate_count',
            new_name='product_count',
        ),
    ]
