# Generated by Django 3.0.4 on 2020-06-15 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_auto_20200615_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcounter',
            old_name='product_id',
            new_name='product',
        ),
    ]
