# Generated by Django 3.0.4 on 2020-04-17 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20200417_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='image_url',
            new_name='image_path',
        ),
    ]
