# Generated by Django 3.0.4 on 2020-04-17 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_auto_20200417_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image_path',
        ),
    ]
